jabardigitalservice/event-management-system

.github/workflows/build-event-service-staging.yml, .github/workflows/ci-event-service.yml
build(init): event service deployment
- title: build(init): event service deployment
- project: jabar super apps
- participants: @iqbal167 @feriahmad 
- screenshot: https://i.ibb.co/Gd2JK0h/Screenshot-2023-10-26-at-13-52-24.png
=> build(init): event service deployment

dashboard/composables/useFetchData.ts
- add response get 
title: change response dummy
=> fix: add dummy response

.github/workflows/build-event-service-staging.yml
=> fix(build): pull request

.github/workflows/build-event-service-staging.yml
fix(build): edit commit message and MR description
=> fix(build): edit commit message and MR description

dashboard/server/api/auth/[...].ts
- Fixing bug when logout didn't really remove all the session
title: Logout Bug Fixing
=> Fix: logout 

service/src/modules/object/endpoint/endpoint.go, service/src/modules/object/endpoint/update_object.go, service/src/modules/object/repository/object.go, service/src/modules/object/repository/repository.go, service/src/modules/object/transport/handler/handler.go, service/src/modules/object/transport/handler/http/router.go, service/src/modules/object/transport/handler/update_object.go, service/src/modules/object/usecase/update_object.go, service/src/modules/object/usecase/usecase.go
- add update object logic
- add update functionality for Object managament
=> Feat(event): Update Function For Object

service/src/modules/object/endpoint/delete_object.go, service/src/modules/object/endpoint/endpoint.go, service/src/modules/object/repository/object.go, service/src/modules/object/repository/repository.go, service/src/modules/object/transport/handler/delete_object.go, service/src/modules/object/transport/handler/http/router.go, service/src/modules/object/usecase/delete_object.go, service/src/modules/object/usecase/usecase.go
- add Delete object logic
- add Delete functionality for Object managament
=> Feat(event): Delete Function For Object

service/src/modules/object/endpoint/endpoint.go, service/src/modules/object/endpoint/get_objects.go, service/src/modules/object/repository/object.go, service/src/modules/object/repository/repository.go, service/src/modules/object/transport/handler/get_objects.go, service/src/modules/object/usecase/get_objects.go, service/src/modules/object/usecase/usecase.go
- add count object logic
- add count functionality for Object managament
- to return count result in response
=> Refactor(event) : fix how get object send response

service/src/modules/object/transport/handler/get_objects.go
- remove code that causes bug when trying to move pages
- to enable to move page in pagination logic
=> fix bug where pagination logic cannot move page

service/src/modules/object/endpoint/endpoint.go, service/src/modules/object/endpoint/update_object_status.go, service/src/modules/object/repository/object.go, service/src/modules/object/repository/repository.go, service/src/modules/object/transport/handler/http/router.go, service/src/modules/object/transport/handler/update_object_status.go, service/src/modules/object/usecase/update_object_status.go, service/src/modules/object/usecase/usecase.go
- add update status object logic
- add update object status functionality for Object managament
=> Feat(event): Update status Function For Object

service/src/modules/object/endpoint/endpoint.go, service/src/modules/object/endpoint/get_object_by_id.go, service/src/modules/object/repository/object.go
- change the way get by id give response
- to give consistent response to user
=> fix(event): fix response sent after get by id

dashboard/components/Base/DataTable/index.vue, dashboard/pages/object/index.vue, dashboard/pages/organisasi/index.vue
- move the action button from the component table to each page
title: Rafactor: action button from the component table to each page
=> Refactor: action button from the component table to each page

service/src/modules/object/repository/object.go
- add logic to concat logo and banner with the storage url
- to give correct path to logo and banner with the storage url
=> Fix(event): concat the logo and banner with the storage url

dashboard/components/Base/DataTable/index.vue, dashboard/composables/useFetchData.ts, dashboard/pages/object/index.vue
-  integration api object on get, delete and publish
title: Integration api object
=> Feat : integration api object

service/go.sum, service/src/modules/object/repository/object.go
- fix the logic to concat logo and banner with the storage url
- to give correct path to logo and banner with the storage url
=> fix path response that is returned to user

service/src/modules/object/transport/handler/http/request/object.go
- remove the logic where start date and end date automatically return today data when not filled
- to show all object correctly and make startdate and end date filter optional
=> Fix(event): remove unnecessary if statement

service/src/modules/object/entity/entity.go, service/src/modules/object/repository/object.go, service/src/modules/object/transport/handler/http/request/object.go, service/src/modules/object/transport/handler/http/response/object.go
- add logic to handle new field
- to handle new field correctly
=> Fix(event): add logic to handle new field

dashboard/server/api/auth/[...].ts
- adding refresh token
title: Add Refresh Token
participants: @rayfajars @johndy2742 @ristianaditya @MNAlfiansyah @marsellavaleria19
=> feat: refresh token

service/src/migration/scripts/000004_create_table_organization.down.sql, service/src/migration/scripts/000004_create_table_organization.up.sql
- add migration script for organizations
- provide table for organizations
=> feat(event): add migration script for organizations

dashboard/components/Base/DataTable/index.vue, dashboard/components/TheSidebar.vue, dashboard/pages/object/index.vue
-  add logo on list table
title: add logo on list table
=> feat : add logo on list table

service/src/constant/constant.go, service/src/modules/modules.go, service/src/modules/object/transport/handler/handler.go, service/src/modules/organization/endpoint/create_organization.go, service/src/modules/organization/endpoint/endpoint.go, service/src/modules/organization/entity/entity.go, service/src/modules/organization/module.go, service/src/modules/organization/repository/object.go, service/src/modules/organization/repository/repository.go, service/src/modules/organization/transport/handler/create_organization.go, service/src/modules/organization/transport/handler/handler.go, service/src/modules/organization/transport/handler/http/request/request.go, service/src/modules/organization/transport/handler/http/response/response.go, service/src/modules/organization/transport/handler/http/router.go, service/src/modules/organization/usecase/create_object.go, service/src/modules/organization/usecase/usecase.go, service/src/services/main.go
- add a new module called organization
- add create functionality for organization managament
Participants: @johndy2742, @iqbal167, @alqinsidev, @ristianaditya , @MNAlfiansyah
=> feat(event) : Create Function For Organization

service/src/modules/organization/endpoint/endpoint.go, service/src/modules/organization/endpoint/get_organization_by_id.go, service/src/modules/organization/entity/entity.go, service/src/modules/organization/repository/object.go, service/src/modules/organization/repository/repository.go, service/src/modules/organization/transport/handler/get_organization_by_id.go, service/src/modules/organization/transport/handler/http/request/request.go, service/src/modules/organization/transport/handler/http/response/response.go, service/src/modules/organization/transport/handler/http/router.go, service/src/modules/organization/usecase/get_organization_by_id.go, service/src/modules/organization/usecase/usecase.go
- add get by id logic for organization 
- fix minor bug in get object
- add get by id functionality for organization managament
=> feat(event): Add get by id  logic for organization

service/src/modules/organization/endpoint/endpoint.go, service/src/modules/organization/endpoint/update_organization.go, service/src/modules/organization/repository/organization.go, service/src/modules/organization/repository/repository.go, service/src/modules/organization/transport/handler/http/router.go, service/src/modules/organization/transport/handler/update_organization.go, service/src/modules/organization/usecase/update_organization.go, service/src/modules/organization/usecase/usecase.go
- add update organization logic
- add update functionality for organization managament
=> feat(event): Add update logic for organization

dashboard/components/Base/DragAndDropFile/index.vue, dashboard/components/Base/Modal/FormAddress.vue, dashboard/components/Object/Form/index.vue, dashboard/composables/useFetchData.ts
- add component form input adress
- add validation upload image
title: Component form input address
=> Feat: Component form input address

service/src/modules/organization/entity/entity.go, service/src/modules/organization/repository/organization.go, service/src/modules/organization/transport/handler/http/request/request.go, service/src/modules/organization/transport/handler/http/response/response.go
- add logic to handle new field
- to handle new field correctly
=> Fix(event): add logic to handle new field 

service/src/migration/scripts/000006_alter_column_organization.down.sql, service/src/migration/scripts/000006_alter_column_organization.up.sql
- add additional field in db
- provide additional field in db
=> refactor(event): add additional field in db

dashboard/components/Base/DragAndDropFile/index.vue, dashboard/components/Base/DragAndDropFileMultiple/index.vue
- fixing drag and drop component to support edit
- fixing drag and drop multiple component to support edit
title: Component Drag And Drop
=> fix: drag and drop component to support on editing

dashboard/components/Base/DataTable/index.vue, dashboard/components/Object/Form/index.vue, dashboard/composables/useFetchData.ts, dashboard/pages/object/form/index.vue, dashboard/pages/object/index.vue, dashboard/store/index.ts
- add feature edit to object
title: Edit Form Object
=> feat: object edit

dashboard/components/Base/Modal/FormAddress.vue, dashboard/components/Organization/Form/index.vue, dashboard/composables/useFetchData.ts, dashboard/pages/organisasi/form/index.vue, dashboard/pages/organisasi/index.vue
- Integration Get, Create, Update and Delete
title: Integration Get, Create, Update and Delete
=> feat: integration get, create, update and delete

dashboard/components/Object/Form/index.vue
- fixing field to implement new APi update
title: Object Form
=> fix: adding new field for API update

dashboard/pages/organisasi/index.vue
- removing detail button on organisasi
title: Organisasi Table
=> refactor: organisasi table minor update

service/src/migration/scripts/000008_integrate_object_organization.down.sql, service/src/migration/scripts/000008_integrate_object_organization.up.sql
- add organization id as FK in objects table
- to make  organization id serve as FK in objects table
https://dbdiagram.io/d/JSA-EVENT-DB-652f5e50ffbf5169f0e8d73f
=> refactor(event): integrate organization table to object table

service/src/modules/object/entity/entity.go, service/src/modules/object/repository/object.go, service/src/modules/object/transport/handler/http/request/object.go, service/src/modules/object/transport/handler/http/response/object.go
- add logic to handle new field
- to handle new field correctly
=> refactor(event): add logic to handle organization id field

service/src/modules/organization/endpoint/delete_organization.go, service/src/modules/organization/entity/entity.go, service/src/modules/organization/repository/organization.go, service/src/modules/organization/transport/handler/create_organization.go, service/src/modules/organization/transport/handler/handler.go, service/src/modules/organization/transport/handler/http/request/request.go, service/src/modules/organization/transport/handler/http/response/response.go
- changes error handling
- adjust naming of struct
- to give better error response
- to have consistency in naming
=> fix(event): fix error handling and adjust naming to have consistency

dashboard/components/Base/TextInput/index.vue, dashboard/components/Base/TextInputGroup/index.vue, dashboard/components/Base/TextareaInput/index.vue
- refactor data just adding to support disabled
title: Component Drag And Drop
=> refactor : text input component support disabled

dashboard/components/Base/Dropdown/index.vue
- Add New Component Dropdown
title: Component Dropdown
=> feat: component dropdown

dashboard/components/Base/DragAndDropFile/index.vue, dashboard/components/Base/DragAndDropFileMultiple/index.vue
- adding validation to drag and drop component 
title: Component Drag And Drop
=> Feat: validate drag and drop component

dashboard/components/Base/Modal/FormAddress.vue
- fixing modal address
title: Component Modal Address
=> fix: component modal address

dashboard/components/Object/Form/index.vue
- integration organization to object
title: Form Object
=> feat: integration organization to object

service/src/modules/object/entity/entity.go, service/src/modules/object/repository/object.go, service/src/modules/object/transport/handler/http/response/object.go
- add logic to handle new field
- to handle new field correctly
=> refactor(event): add logic to get organization name from organization table

dashboard/components/Base/DragAndDropFile/index.vue, dashboard/components/Object/Form/index.vue
- refactor layouting form object
title: Form Object
=> Refactor: object form layout

dashboard/components/Base/DragAndDropFile/index.vue
- fixing drag and drop error when uploading
title: Component Drag And Drop
=> Fix: drag and drop fixing

dashboard/components/Base/Modal/FormAddress.vue
- fixing error address modal
title: Component Address Modal
=> fix: address modal

dashboard/components/Base/Dropdown/index.vue
- fixing dropdown auto select on edit 
title: Component Dropdown
=> fix: dropdown component

dashboard/components/Base/Dropdown/index.vue, dashboard/components/Base/Modal/FormAddress.vue, dashboard/components/Base/Modal/index.vue, dashboard/components/Base/TextInput/index.vue, dashboard/components/Base/TextInputGroup/index.vue, dashboard/components/Base/TextareaInput/index.vue
- change color all component to blue
title: Change Color of Component
=> refactor: design color component

service/src/app/app.go, service/src/app/config.go, service/src/app/logger.go, service/src/migration/scripts/000009_create_table_category.up.sql, service/src/modules/object/endpoint/create_object.go, service/src/modules/object/endpoint/endpoint.go, service/src/modules/object/repository/object.go, service/src/modules/object/repository/repository.go, service/src/modules/object/usecase/create_object.go, service/src/modules/object/usecase/usecase.go
- add logger file and remove redudant import in app.go
- ensure the application is ready to address future logging requirements, such as debugging, error tracking, and performance monitoring.
=> feat(event): add logger file

dashboard/components/Base/DataTable/index.vue, dashboard/components/Object/Form/index.vue, dashboard/components/Organization/Form/index.vue
- Fix missing code on conflict
title: Fix Conflict
=> fix: conflict error

service/src/app/app.go, service/src/modules/object/endpoint/create_object.go, service/src/modules/object/usecase/usecase.go
- add log initialization to fix response bug 
- fix bug where data is inserted succesfully it return 500 error
=> fix(event): response bug

service/src/constant/constant.go, service/src/modules/category/endpoint/create_category.go, service/src/modules/category/endpoint/endpoint.go, service/src/modules/category/entity/entity.go, service/src/modules/category/module.go, service/src/modules/category/repository/category.go, service/src/modules/category/repository/repository.go, service/src/modules/category/transport/handler/create_category.go, service/src/modules/category/transport/handler/handler.go, service/src/modules/category/transport/handler/http/request/category.go, service/src/modules/category/transport/handler/http/response/category.go, service/src/modules/category/transport/handler/http/router.go, service/src/modules/category/usecase/create_category.go, service/src/modules/category/usecase/usecase.go, service/src/modules/modules.go, service/src/modules/object/endpoint/endpoint.go, service/src/modules/object/repository/repository.go, service/src/modules/object/transport/handler/http/router.go, service/src/modules/object/usecase/usecase.go, service/src/modules/organization/transport/handler/http/router.go, service/src/services/main.go
- add a new module called category
- add create functionality for category managament
Participants: @johndy2742, @iqbal167, @alqinsidev, @ristianaditya , @MNAlfiansyah
=> feat(event) : Create Function For Category

service/src/modules/category/endpoint/endpoint.go, service/src/modules/category/endpoint/get_categories.go, service/src/modules/category/repository/category.go, service/src/modules/category/repository/repository.go, service/src/modules/category/transport/handler/get_categories.go, service/src/modules/category/transport/handler/http/request/category.go, service/src/modules/category/transport/handler/http/router.go, service/src/modules/category/usecase/get_categories.go, service/src/modules/category/usecase/usecase.go
- add get category logic
- add get functionality for category managament
=> feat(event) : Get Function For Category

service/src/modules/category/endpoint/endpoint.go, service/src/modules/category/endpoint/update_category.go, service/src/modules/category/repository/category.go, service/src/modules/category/repository/repository.go, service/src/modules/category/transport/handler/http/router.go, service/src/modules/category/transport/handler/update_category.go, service/src/modules/category/usecase/update_category.go, service/src/modules/category/usecase/usecase.go
- add update category logic
- add update functionality for category managament
=> feat(event): Add update logic for category

service/src/modules/category/endpoint/endpoint.go, service/src/modules/category/endpoint/get_category_by_id.go, service/src/modules/category/repository/category.go, service/src/modules/category/repository/repository.go, service/src/modules/category/transport/handler/get_category_by_id.go, service/src/modules/category/transport/handler/http/router.go, service/src/modules/category/usecase/get_category_by_Id.go, service/src/modules/category/usecase/usecase.go
- add get by id logic for category
- add get by id functionality for category managament
=> feat(event): Add get by id logic for category

service/src/modules/category/endpoint/delete_category.go, service/src/modules/category/endpoint/endpoint.go, service/src/modules/category/repository/category.go, service/src/modules/category/repository/repository.go, service/src/modules/category/transport/handler/delete_category.go, service/src/modules/category/transport/handler/http/router.go, service/src/modules/category/usecase/delete_categry.go, service/src/modules/category/usecase/usecase.go
- add delete category logic
- add delete functionality for category managament
=> Feat(event): add delete function for category

dashboard/common/constant/navigation.js, dashboard/components/Object/Form/index.vue, dashboard/components/Organization/Form/index.vue, dashboard/layouts/default.vue, dashboard/layouts/headerBase.vue, dashboard/pages/object/detail/index.vue, dashboard/pages/object/form/index.vue, dashboard/pages/organisasi/form/index.vue
- fix width form
- refactor layout default 
title: refactor layout default 
=> Refactor : layout default

dashboard/components/Base/Dropdown/index.vue, dashboard/components/Base/Modal/FormAddress.vue, dashboard/components/Base/TextInput/index.vue, dashboard/components/Base/TextInputGroup/index.vue, dashboard/components/Base/TextareaInput/index.vue, dashboard/components/Object/Form/index.vue, dashboard/components/Organization/Form/index.vue
- adding address view on form
title: Address of form
=> feat: show address on form

dashboard/app.config.ts, dashboard/components/Base/DragAndDropFile/index.vue, dashboard/components/Base/DragAndDropFileMultiple/index.vue
- fixing cropping image on component drag and drop 
- change the primary color to blue
title: refactor layout default 
=> fix: drag and drop image crop

dashboard/common/constant/navigation.js, dashboard/common/constant/object.ts, dashboard/common/constant/organisasi.ts, dashboard/components/Base/DataTable/index.vue, dashboard/layouts/default.vue, dashboard/layouts/headerBase.vue, dashboard/nuxt.config.ts, dashboard/pages/object/index.vue, dashboard/pages/organisasi/index.vue
- fix title page 
- remove dashboard
- fix number iteration table
title :Fix title, sidebar, number table
=> Fix: title, sidebar, number table

service/src/modules/object/endpoint/delete_object.go, service/src/modules/object/endpoint/get_object_by_id.go, service/src/modules/object/endpoint/get_objects.go, service/src/modules/object/endpoint/update_object.go, service/src/modules/object/endpoint/update_object_status.go, service/src/modules/object/repository/object.go, service/src/modules/object/repository/repository.go, service/src/modules/object/usecase/delete_object.go, service/src/modules/object/usecase/get_object_by_id.go, service/src/modules/object/usecase/get_objects.go, service/src/modules/object/usecase/update_object.go, service/src/modules/object/usecase/update_object_status.go
- add logger in object module
- to log every activity in object module
=> feat(event): add logger to rest of object module

dashboard/components/Object/Detail/Pengaturan/index.vue, dashboard/components/Object/Detail/Profile/index.vue, dashboard/components/Object/Form/index.vue, dashboard/components/Organization/Form/index.vue, dashboard/pages/object/index.vue, dashboard/pages/organisasi/index.vue, dashboard/utils/index.ts
- refactor change toast logic 
- fix width banner object
title : refactor change toast logic 
=> Refactor: toast

dashboard/components/Base/DragAndDropFile/index.vue, dashboard/pages/login/index.vue
- fix redirect login
- fix error when uploading logo
title : Refactor drag and drop and redirect login
=> Refactor: dragandrop and redirect login
